pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "label=auto merge"
      - "check-success=check"
      - "#check-failure=0"
    actions:
      merge:
        method: rebase
